#!/usr/bin/env bash

LOGFILE="$PWD"/outputs/output.log
FLASK_APP="tweet-search-app.py"

if [ "$(echo "$FILE1" | awk -F"/" '{print $NF}')" == $FLASK_APP ] 
	then
	nohup python3 "$1" > $LOGFILE 2>&1
	shopt -s huponexit
else
	nohup python3 ${1:+"$@"} > $LOGFILE 2>&1
	shopt -s huponexit
fi

